### ISSUE TITLE
Inicijalni komentari

### ISSUE THREAD

**Issue by milicakarlicic** [MATF-Software-Verification/2023_Analysis_fire-and-water#1]
- [x] modifikacija makefile-a
- [x] dodati #ifndef za Qt dijelove originalnog koda
- [x] dodati .tex 
- [x] https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/issues/1#issuecomment-1412155883
- [x] https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/issues/1#issuecomment-1412159187
- [x] https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/issues/1#issuecomment-1412165218
- [x] https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/issues/1#issuecomment-1412169048

**Comment by ivan-ristovic** [comment]
Mozemo li da obrisemo [ovaj folder](https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/tree/main/ProjectAnalysisReport/v1)?

**Comment by ivan-ristovic** [comment]
Umesto [direktorijuma sa modifikovanim projektom](https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/tree/main/ModifiedFireAndWater), dovoljno je samo uraditi `git diff` i postaviti fajl sa razlikama na repozitorijum - nema razloga da drzimo modifikovanu kopiju citavog fire-and-water repozitorijuma. 
Alternativno, napraviti licni fork fire-and-water projekta, ubaciti izmene, i dodati taj repozitorijum kao jos jedan submodul u ovaj.

**Comment by ivan-ristovic** [comment]
Bilo bi lepo ukljuciti i tekstualni izlaz Clang-a, Clang-Tidy-a i Clazy-a. Eventualno i skript kako se pokrecu - bice korisno kolegama ubuduce :)

**Comment by ivan-ristovic** [comment]
Slike iz [ProjectAnalysisReport](https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/tree/main/ProjectAnalysisReport) direktorijuma vec postoje u roditeljskim folderima, zar ne? Mozemo ih ukloniti odatle i ukljuciti vec postojece u tex? Na primer:
https://github.com/MATF-Software-Verification/2023_Analysis_fire-and-water/blob/a923f90181d3f8fd5fc3690ddf52bfd5386ccf17/ProjectAnalysisReport/ProjectAnalysisReport.tex#L118
Mozemo zameniti sa:
```tex
\includegraphics[scale=0.5]{../Valgrind/Memcheck/mem1.png}
```

Slicno i za ostale slike.

**Comment by ivan-ristovic** [comment]
Dodao sam checklist u tekst tiketa tako da mozemo da pratimo sve.
